baseURL = "https://notbinary.github.io/mhclg-epc-alpha"
languageCode = "en-uk"
title = "EPC Alpha"
theme = "govuk"
googleAnalytics = ""
publishDir = "../docs"


staticDir = ["static", "src/govuk_template/assets", "src/govuk_elements/assets"]

[params]
  global_header_text = "GOV.UK"
  servicename = "EPC Alpha"
  #users = ["Data Maintainer", "Data Modeller", "Policy Maker", "PropTech"]

  # Nav links in the side bar
  [[params.propositionlinks]]
  name = "Overview"
  url = "/overview/"
  currentpage = true

  [[params.propositionlinks]]
  name = "User Research"
  url = "/user-research/"

  [[params.propositionlinks]]
  name = "Prototypes"
  url = "/prototype/"

  [[params.propositionlinks]]
  name = "Beta requirements"
  url = "/beta/"

  [[params.propositionlinks]]
  name = "Weeknotes"
  url = "/week-notes/"

  [[params.propositionlinks]]
  name = "Guidance & Standards"
  url = "/guidance-and-standards/"


[taxonomies]
  tag = "tags"
  pattern = "patterns"
